# Generated by Django 3.0.4 on 2021-01-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacancy', '0004_addResume_and_littleadditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='skills',
            field=models.TextField(),
        ),
    ]
