# Generated by Django 3.0.4 on 2021-02-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacancy', '0005_change_published_at_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
